<?php

return [
    'FriendlyName' => [
        'Type' => 'System',
        'Value' => 'Kredi Karti - YapiKredi',
    ],
    'UsageNotes' => [
        'Type' => 'System',
        'Value' => 'Modul Dokumantasyonu: <a href="https://github.com/aybarsm/whmcs-yapikredi" target="_blank">https://github.com/aybarsm/whmcs-yapikredi</a><br><br>Hata Bildirimi: <a href="https://github.com/aybarsm/whmcs-yapikredi/issues" target="_blank">https://github.com/aybarsm/whmcs-yapikredi/issues</a>',
    ],
    'MERCHANT_ID' => [
        'FriendlyName' => 'YKB Uye Isyeri Numarasi',
        'Type' => 'text',
        'Size' => '25',
        'Default' => '',
        'Description' => '10 haneli YKB uye isyeri numarasi',
    ],
    'TERMINAL_ID' => [
        'FriendlyName' => 'YKB Uye Isyeri Terminal Numarasi',
        'Type' => 'text',
        'Size' => '25',
        'Default' => '',
        'Description' => '8 haneli YKB uye isyeri terminal numarasi',
    ],
    'POSNET_ID' => [
        'FriendlyName' => 'YKB Uye Isyeri Posnet Numarasi',
        'Type' => 'text',
        'Size' => '25',
        'Default' => '',
        'Description' => '16 haneye kadar YKB uye isyeri POSNET numarasi',
    ],
    'ENCKEY' => [
        'FriendlyName' => 'Sifreleme Anahtari',
        'Type' => 'password',
        'Size' => '30',
        'Default' => '',
        'Description' => 'Sifreleme anahtari',
    ],
    'TEST_ENCKEY' => [
        'FriendlyName' => 'Test Ortami - Sifreleme Anahtari',
        'Type' => 'text',
        'Size' => '30',
        'Default' => '10,10,10,10,10,10,10,10',
        'Description' => 'Test modunda kullanilacak sifreleme anahtari <b>(Test ortami icin sabittir)</b>',
    ],
    'OOS_TDS_SERVICE_URL' => [
        'FriendlyName' => 'Banka 3D Secure Adresi',
        'Type' => 'text',
        'Size' => '50',
        'Default' => 'https://posnet.yapikredi.com.tr/3DSWebService/YKBPaymentService',
        'Description' => '3D secure banka sayfasi adresi',
    ],
    'TEST_OOS_TDS_SERVICE_URL' => [
        'FriendlyName' => 'Test Ortami - Banka 3D Secure Adresi',
        'Type' => 'text',
        'Size' => '50',
        'Default' => 'https://setmpos.ykb.com/3DSWebService/YKBPaymentService',
        'Description' => 'Test modunda kullanilacak 3D secure banka sayfasi adresi',
    ],
    'XML_SERVICE_URL' => [
        'FriendlyName' => 'Banka XML Servisi Adresi',
        'Type' => 'text',
        'Size' => '50',
        'Default' => 'https://posnet.yapikredi.com.tr/PosnetWebService/XML',
        'Description' => 'Banka entegrasyon servis adresi',
    ],
    'TEST_XML_SERVICE_URL' => [
        'FriendlyName' => 'Test Ortami - Banka XML Servisi Adresi',
        'Type' => 'text',
        'Size' => '50',
        'Default' => 'https://setmpos.ykb.com/PosnetWebService/XML',
        'Description' => 'Test modunda kullanilacak banka entegrasyon servis adresi',
    ],
    'MERCHANT_INIT_URL' => [
        'FriendlyName' => 'Uye Isyeri Adresi',
        'Type' => 'text',
        'Size' => '50',
        'Default' => $initUrl = \Aybarsm\Whmcs\Service\Whmcs::getSystemUrl(),
        'Description' => 'Uye isyerinin islem yaptigi web sitesi adresi',
    ],
    'MERCHANT_RETURN_URL' => [
        'FriendlyName' => 'Uye Isyeri Geri Yonlendirme Adresi',
        'Type' => 'text',
        'Size' => '50',
        'Default' => (! empty($initUrl) ? "{$initUrl}/modules/gateways/callback/" . \WHMCS\Module\Gateway\YapiKredi\Posnet::getIdentifier() . '.php' : ''),
        'Description' => 'Form yonlendirmesinin geri yapilacagi isyeri sayfa adresi </b>(Max 255 karakter)</b>' . (empty($initUrl) ? ' http(s)://WHMCS_ADRESI/modules/gateways/callback/' . \WHMCS\Module\Gateway\YapiKredi\Posnet::getIdentifier() . '.php' : ''),
    ],
    'XID_PREFIX' => [
        'FriendlyName' => 'Tekil Islem On Eki',
        'Type' => 'text',
        'Size' => '30',
        'Default' => 'YKB',
        'Description' => 'Tekil islem kimlikleyicide kullanilacak on ek. (XID)',
    ],
    'TEST_XID_PREFIX' => [
        'FriendlyName' => 'Test Ortami - Tekil Islem On Eki',
        'Type' => 'text',
        'Size' => '30',
        'Default' => 'YKBTEST',
        'Description' => 'Tes modunda tekil islem kimlikleyicide kullanilacak on ek. (XID)',
    ],
    'TRANSACTION_TYPE' => [
        'FriendlyName' => 'Kredi Karti Varsayilan Islem Tipi',
        'Type' => 'dropdown',
        'Options' => [
            'Sale' => 'Satis',
            'Auth' => 'Provizyon',
        ],
        'Description' => 'Varsayilan kredi karti islem tipi. <b>(Detayli bilgi icin lutfen Posnet entegrasyon dokumanlarini inceleyin.)</b>',
        'Default' => 'Sale',
    ],
    'CURRENCY_CODE' => [
        'FriendlyName' => 'Varsayilan Para Birimi',
        'Type' => 'dropdown',
        'Options' => [
            'TL' => 'TRY',
            'US' => 'USD',
            'EU' => 'EUR',
            'DYNAMIC' => 'Dinamik',
        ],
        'Description' => 'Islem yapilacak para birimi. <b>(Dinamik: Kullanici hesabina tanimli param biriminden otomatik olarak cozumlenir, cozumlenemez ise CURRENCY_CODE_FALLBACK parametresi kullanilir.)</b>',
        'Default' => 'DYNAMIC',
    ],
    'CURRENCY_CODE_FALLBACK' => [
        'FriendlyName' => 'Yedek Para Birimi',
        'Type' => 'dropdown',
        'Options' => [
            'TL' => 'TRY',
            'US' => 'USD',
            'EU' => 'EUR',
        ],
        'Description' => 'Para birimi dinamik olmasi ancak para biriminin cozumlenememesi halinde varsayilan olarak kullanilacak para birimi.',
        'Default' => 'TL',
    ],
    'REFUND_ENABLED' => [
        'FriendlyName' => 'Iade Fonksiyonlari',
        'Type' => 'dropdown',
        'Options' => [
            'YES' => 'Aktif',
            'NO' => 'Devre Disi',
        ],
        'Description' => 'Iade fonksiyonlari kullanilabilir olacak mi?',
        'Default' => 'NO',
    ],
    'PROCESS_FEE_STATIC' => [
        'FriendlyName' => 'Banka Komisyonu - Statik (Deger)',
        'Type' => 'text',
        'Size' => '15',
        'Default' => '0',
        'Description' => 'Basarili odeme islemlerinde isyeri icin dogan statik islem gider tutari. <b>(Oran ile birlikte kullanilabilir.) (0: Devre disi / Ondalik ayraci nokta [.])</b>',
    ],
    'PROCESS_FEE_RATE' => [
        'FriendlyName' => 'Banka Komisyonu - Oran (%)',
        'Type' => 'text',
        'Size' => '15',
        'Default' => '0',
        'Description' => 'Basarili odeme islemlerinde isyeri icin dogan statik islem gider orani. <b>(Statik ile birlikte kullanilabilir.) (0: Devre disi / Ondalik ayraci nokta [.])</b>',
    ],
    'PAYMENT_BLOCKED_DAYS' => [
        'FriendlyName' => 'Banka Odeme Bloke Gun Sayisi',
        'Type' => 'text',
        'Size' => '15',
        'Default' => '45',
        'Description' => 'Basarili odeme islemlerinde isyeri icin dogan bloke gun sayisi. <b>(0: Devre disi)</b>',
    ],
    'TEST_MODE' => [
        'FriendlyName' => 'Test Modu',
        'Size' => '10',
        'Type' => 'dropdown',
        'Options' => [
            'YES' => 'Aktif',
            'NO' => 'Devre Disi',
        ],
        'Description' => 'Islemler test modunda mi gerceklestirilsin?',
        'Default' => 'YES',
    ],
    '3DSECURE_IFRAME' => [
        'FriendlyName' => '3D Secure Iframe',
        'Size' => '10',
        'Type' => 'dropdown',
        'Options' => [
            'YES' => 'Iframe Kullan',
            'NO' => 'Banka Sayfasina Yonlendir',
        ],
        'Description' => '3D secure isleminin iframe icerisinde mi yoksa banka sayfasinda yapilacagini belirleyen ayar.',
        'Default' => 'NO',
    ],
    'BANK_LANG' => [
        'FriendlyName' => 'Banka Dili',
        'Size' => '10',
        'Type' => 'dropdown',
        'Options' => [
            'TR' => 'Turkce',
            'EN' => 'Ingilizce',
            'DYNAMIC' => 'Dinamik',
        ],
        'Description' => 'Banka ekranlarinda kullanilacak dil. <b>(Dinamik: Kullanici hesap dili Turkce ya da kayitli ulkesi Turkiye ise Turkce, diger tum diller ve ulkeler Ingilizce olarak uygulanir.)</b>',
        'Default' => 'DYNAMIC',
    ],
    'REQUEST_AGENT' => [
        'FriendlyName' => 'HTTP Agent',
        'Type' => 'text',
        'Size' => '50',
        'Default' => 'Aybarsm WHMCS-YapiKredi/2023; (' . PHP_OS . ')',
        'Description' => 'XML servisine gonderilen HTTP isteklerinde gozukecek agent bilgisi',
    ],
];